/**
 * Converts the logo lettering to SVG paths (Plus Jakarta Sans), so the logo
 * never depends on a loaded font. Writes src/components/brand/paths.ts.
 * Run with `npm run logo-paths` (only needed if the lettering changes).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import opentype from 'opentype.js'

const fontFile = (weight: number) =>
  `node_modules/@fontsource/plus-jakarta-sans/files/plus-jakarta-sans-latin-${weight}-normal.woff`

const load = (weight: number) => {
  const buffer = readFileSync(fontFile(weight))
  return opentype.parse(buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength))
}

const round = (n: number) => Math.round(n * 100) / 100

/**
 * Lays out `text` at `size` units with `tracking` (em), baseline at y = 0,
 * then shifts it so its ink starts at (0, 0).
 */
function lettering(font: opentype.Font, text: string, size: number, tracking: number) {
  // Glyph by glyph: no OpenType substitutions needed for plain lowercase.
  const glyphs = [...text].map((char) => font.charToGlyph(char))
  const scale = size / font.unitsPerEm
  const path = new opentype.Path()
  let x = 0
  glyphs.forEach((glyph, index) => {
    path.extend(glyph.getPath(x, 0, size))
    const next = glyphs[index + 1]
    x += (glyph.advanceWidth ?? 0) * scale + tracking * size
    if (next) {
      x += font.getKerningValue(glyph, next) * scale
    }
  })

  // Serialised by hand, shifted so the ink starts at (0, 0) (opentype's
  // toPathData can emit NaN for some quadratic segments).
  const box = path.getBoundingBox()
  const px = (x: number) => round(x - box.x1)
  const py = (y: number) => round(y - box.y1)
  const d = path.commands
    .map((c) => {
      switch (c.type) {
        case 'M':
        case 'L':
          return `${c.type}${px(c.x)} ${py(c.y)}`
        case 'Q':
          return `Q${px(c.x1)} ${py(c.y1)} ${px(c.x)} ${py(c.y)}`
        case 'C':
          return `C${px(c.x1)} ${py(c.y1)} ${px(c.x2)} ${py(c.y2)} ${px(c.x)} ${py(c.y)}`
        default:
          return 'Z'
      }
    })
    .join('')

  const capHeight = ((font.tables.os2 as { sCapHeight?: number }).sCapHeight ?? 0) * scale
  const xHeight = ((font.tables.os2 as { sxHeight?: number }).sxHeight ?? 0) * scale
  return {
    d,
    width: round(box.x2 - box.x1),
    height: round(box.y2 - box.y1),
    /** Distance from the top of the ink to the baseline. */
    baseline: round(-box.y1),
    capHeight: round(capHeight),
    xHeight: round(xHeight),
  }
}

const semibold = load(600)
const bold = load(700)

const wordmark = lettering(semibold, 'samatrica', 100, -0.01)
const s = lettering(bold, 's', 100, 0)

writeFileSync(
  'src/components/brand/paths.ts',
  `// Generated by scripts/logo-paths.ts from Plus Jakarta Sans. Do not edit.

/** "samatrica", SemiBold, 100-unit type, tracking -0.01em; ink starts at (0, 0). */
export const wordmark = ${JSON.stringify(wordmark, null, 2)}

/** A Bold "s" for the icon; ink starts at (0, 0). */
export const letterS = ${JSON.stringify(s, null, 2)}
`,
)
console.log('Wrote src/components/brand/paths.ts', { wordmark: [wordmark.width, wordmark.height], s: [s.width, s.height] })
